### ISSUE TITLE
Problematic Input File Logging

### ISSUE THREAD

**Issue by keithjjones** [cisagov/ACID#3]
https://github.com/cisagov/ACID/blob/123d738fd3c3f5eeab1ee24ece6ed3592ad79600/scripts/ACID_input.zeek#L41

This is problematic as it will report input files for other packages.  

```
worker-30: 1723068885.808554 /opt/corelight/share/zeek/site/packages/ACID/ACID_input.zeek, line 46: INFO: ACID Input file loaded: /opt/REDACTED/share/zeek/site/packages/NOTACIDPACKAGE/SomeData.compact.json
```

**Comment by jsteele-1** [comment]
Updated input logging code to check for ACID specific input files before reporting. 
Commit: https://github.com/cisagov/ACID/commit/575ca1e14d4d20291aad82fcd6ac3dccea1443e4
